Fix for File Chameleon
Ensembl/format-transcriber pull request #10
Opened 2023-05-16 14:17 UTC by nwillhoft

In Ensembl Release 96, changes were applied to this repo which broke the File Chameleon tool. This PR has been created to fix these breaking changes so that Web no longer have to apply their hack.

A related PR in `ensembl-io` will also be created for this File Chameleon fix.

JIRA tickets with extra information:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5060
https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-3150

2023-05-23 09:29 UTC, nwillhoft commented
Some white space changes have been made. Some if statement contents were not indenting properly because only a single tab had been used (which was defaulting to 8 spaces in vim and 4 spaces in VS code), so I've replaced with the correct number of spaces to ident the code properly in each case.

2023-06-16 13:55 UTC, EbiArnie requested changes

2023-06-16 13:55 UTC, EbiArnie commented on lib/Bio/FormatTranscriber.pm
> +	    $self->write_record($rec);
Is it on purpose that we drop the 'unless' part here?

2023-06-16 13:55 UTC, EbiArnie commented on lib/Bio/FormatTranscriber.pm
> +    #print "Attemping to get serializer by type: $type\n";
Please remove commented out part.

2023-06-19 13:31 UTC, nwillhoft commented on lib/Bio/FormatTranscriber.pm
> +	    $self->write_record($rec);
Yes, I had dropped this on purpose during testing. I had found that the record object wasn't being printed out if I didn't remove the `unless($rec->{delete});`.

2023-06-26 10:31 UTC, EbiArnie requested changes

2023-06-26 10:31 UTC, EbiArnie commented on lib/Bio/FormatTranscriber.pm
> +	    $self->write_record($rec);
If you look into
FormatTranscriber/Processor/FieldBased.pm line 348, we set delete if we want to remove records.
I think this is part of the filtering functionality.
I'm not convinced this can just go.

2023-06-27 12:46 UTC, nwillhoft commented on lib/Bio/FormatTranscriber.pm
> +	    $self->write_record($rec);
Thanks a lot for pointing out my mistake here. The filtering functionality is indeed removed if this code snippet is removed. Having put it back in, I've re-run jobs on the updated File Chameleon web tool. I did some line counts of files and can see that previous results had no filtering applied, however now they do.

My investigations into checking filtering, and also checking id conversion for completeness, can be found in these tickets, respectively: https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-4223 and https://www.ebi.ac.uk/panda/jira/browse/ENSCORESW-4224.

2023-06-27 15:12 UTC, EbiArnie approved these changes

2023-06-28 10:04 UTC, merged